# Generated by Django 3.2.10 on 2022-08-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
