# Generated by Django 3.1.6 on 2022-08-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthSystem',
        ),
    ]
