# Generated by Django 3.1.6 on 2022-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220810_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authnumber',
            field=models.IntegerField(default=0),
        ),
    ]
