# Generated by Django 3.1.6 on 2022-08-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_authnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authnumber',
        ),
    ]
