# Generated by Django 4.1 on 2022-08-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
