# Generated by Django 4.1 on 2022-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspolicy',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newspolicy',
            name='url',
            field=models.TextField(),
        ),
    ]
