# Generated by Django 3.2.10 on 2022-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrunkDriving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('county', models.CharField(max_length=45)),
                ('acc_cnt', models.IntegerField()),
                ('death_cnt', models.IntegerField()),
                ('injuries_cnt', models.IntegerField()),
            ],
        ),
    ]
