# Generated by Django 4.1 on 2022-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='awareness',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('category', models.CharField(max_length=50)),
        #         ('very_safe', models.IntegerField()),
        #         ('relatively_safe', models.IntegerField()),
        #         ('normal', models.IntegerField()),
        #         ('relatively_unsafe', models.IntegerField()),
        #         ('very_unsafe', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='earthquake',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('latitude', models.FloatField()),
        #         ('longitude', models.FloatField()),
        #         ('distance_from_seoul', models.FloatField()),
        #         ('scale', models.FloatField()),
        #         ('epicenter', models.TextField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='earthquake_resistance',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('category', models.CharField(max_length=50)),
        #         ('type', models.CharField(max_length=20)),
        #         ('total_building', models.IntegerField()),
        #         ('resistance_required_building', models.IntegerField()),
        #         ('resistance_equipped_building', models.IntegerField()),
        #         ('resistance_unequipped_building', models.IntegerField()),
        #         ('rate_of_total_building', models.FloatField()),
        #         ('rate_of_required_building', models.FloatField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='shelter',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('area', models.CharField(max_length=20)),
        #         ('shelter_name', models.CharField(max_length=40)),
        #         ('detail_address', models.TextField()),
        #         ('acceptance_area', models.IntegerField()),
        #         ('people_capacity', models.IntegerField()),
        #     ],
        # ),
    ]
