# Generated by Django 4.1 on 2022-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('total', models.IntegerField()),
                ('korean', models.IntegerField()),
                ('foreign', models.IntegerField()),
                ('senior', models.IntegerField()),
            ],
        ),
    ]
