# Generated by Django 4.1 on 2022-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_calltaxi_time_pos_proccessed_receipttime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seoul_temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('area', models.CharField(max_length=10)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
            ],
        ),
    ]
