# Generated by Django 4.1 on 2022-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_seoul_dust'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_time_pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('cartype', models.CharField(max_length=20)),
                ('receipttime', models.TextField()),
                ('settime', models.TextField()),
                ('ridetime', models.TextField()),
                ('startpos', models.CharField(max_length=10)),
                ('endpos', models.CharField(max_length=10)),
            ],
        ),
    ]
