# Generated by Django 4.1 on 2022-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_test_time_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='calltaxi_iot_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.TextField()),
                ('on_time', models.DateField()),
                ('off_time', models.DateField()),
                ('safe_rate', models.IntegerField()),
                ('acceleration', models.IntegerField()),
                ('deceleration', models.IntegerField()),
                ('speeding', models.IntegerField()),
                ('ride_time', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='CarAcc',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('year', models.IntegerField()),
        #         ('acc_cl_name', models.CharField(max_length=48)),
        #         ('place_code', models.CharField(max_length=48)),
        #         ('acc_cnt', models.IntegerField()),
        #         ('acc_rate', models.FloatField()),
        #         ('deaths_cnt', models.IntegerField()),
        #         ('injuries_cnt', models.IntegerField()),
        #         ('injuries_rate', models.FloatField()),
        #         ('speeding_cnt', models.IntegerField(blank=True)),
        #         ('center_line_cnt', models.IntegerField(blank=True)),
        #         ('sig_violation_cnt', models.IntegerField(blank=True)),
        #         ('unsafe_distance_cnt', models.IntegerField(blank=True)),
        #         ('unsafe_driving_cnt', models.IntegerField(blank=True)),
        #         ('violation_ped_prt_cnt', models.IntegerField(blank=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='DrunkDriving',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('year', models.IntegerField()),
        #         ('county', models.CharField(max_length=45)),
        #         ('acc_cnt', models.IntegerField()),
        #         ('deaths_cnt', models.IntegerField()),
        #         ('injuries_cnt', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Oldmanacc',
        #     fields=[
        #         ('id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('year', models.IntegerField()),
        #         ('place_id', models.IntegerField()),
        #         ('city_and_county_name', models.CharField(max_length=48)),
        #         ('acc_point', models.CharField(max_length=128)),
        #         ('occurrence_cnt', models.IntegerField()),
        #         ('deaths_cnt', models.IntegerField()),
        #         ('serious_injuries_cnt', models.IntegerField()),
        #         ('slight_injuries_cnt', models.IntegerField()),
        #         ('longitude', models.FloatField()),
        #         ('latitude', models.FloatField()),
        #     ],
        # ),
    ]
