# Generated by Django 3.2.10 on 2022-08-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='processing_status',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='board',
            name='request_data_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
