# Generated by Django 4.1 on 2022-08-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_answer_alter_post_processstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ProcessStatus',
            new_name='ProcessingStatus',
        ),
    ]
