# Generated by Django 3.2.10 on 2022-08-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_processstatus_post_processingstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='BoardType',
            new_name='board_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Contents',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ProcessingStatus',
            new_name='processing_status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='RequestDataType',
            new_name='request_data_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
